### ISSUE TITLE
UEFI unable to mount root FS

### ISSUE THREAD

**Issue by Prezto** [deadhead420/arch-linux-anywhere#257] opened 2017-03-26 16:28 UTC
First of all. Great work making arch faster to install. On my Lenovo X1 Carbon it all works fine.

I recently bought an HP stream 14-ax101nd. I am encountering issues when booting the  Arch-anywhere image from a USB drive. 

This is a list of the things I  tried to make it boot:
- Disable secure boot
- Disable TPM 

When it boots the image It drops me into a rootfs shell. It times out and can't seem to mount the root for some reason. 

I need to inform you I am a simple Linux user with only RHCSA and LPIC-1. Please let me know what information I can provide to fix this issue together.

**Comment by deadhead420** [comment] 2017-03-28 03:02
Does it show any error message? Also what utility did you use to create bootable USB?

**Comment by Prezto** [comment] 2017-04-03 15:38
I managed to get it installed by creating a USB stick using dd with the Arch-anywhere installation on my Lenovo X1 Carbon.

When i use the Windows utility i cannot get it to work properly. Could this be an issue when the vbox option is enabled when using Linux Live USB Creator?

At this moment i am not in the country. As soon as i get back i can test this for you if you would like me to. Then you can add the comment to the download page.

Let me know if i should test this.

Thanks for the great work and not telling me to TRFM.

**Comment by sdeleuze** [comment] 2017-05-08 17:40
Does it use an NVMe SSD? If yes it could be a duplicate of #326.

**Comment by ptrj** [comment] 2017-05-08 18:58
3 partition on SATA SSD Disk:
```
512 FAT32 EFI
400GB /
16GB SWAP
```

[arch-anywhere.txt](https://github.com/deadhead420/arch-linux-anywhere/files/984552/arch-anywhere.txt)

**Comment by Prezto** [comment] 2017-05-08 20:44
It used a soldered on flash chip as storage. The specs tell me EMMC.

On May 8, 2017 19:40, "Sébastien Deleuze" <notifications@github.com<mailto:notifications@github.com>> wrote:

Does it use an NVMe SSD? If yes it could be a duplicate of #326<https://github.com/deadhead420/arch-linux-anywhere/issues/326>.

**Comment by sdeleuze** [comment] 2017-05-09 09:13
@ptrj The error message you have in the logs is related to #319, if you select Update Arch Anywhere before running the install it should be fixed.

@Prezto Could you print the result of `fdisk -l` to allow me to see the name for the SSD drive ?

**Comment by ptrj** [comment] 2017-05-09 09:19
@sdeleuze Thanks

**Comment by Alechi** [comment] 2017-07-18 20:15
I have same problem with arch linux, only bootloader i have been able to boot is rEFInd(simple boot option assigned to PARTUUID), in my case drive is mmcblk0.

**Comment by Alechi** [comment] 2017-07-18 20:19
I have tried with all setups in arch anywhere and there are 2 outcomes depending what bootloader i use: 1. Just boots to usb and doesnt show any other options in bios.  2. /dev/mmcblk0p2(root) timeouts

**Comment by Alechi** [comment] 2017-07-18 21:45
Found solution, install with uefi support using efistub. After install reboot and it drops you to emmercency shell. Now edit fstab so it uses PARTUUIDs instead of device paths or UUIDs.

**Closed** 2017-08-18 22:33 UTC
