### ISSUE TITLE
Username

### ISSUE THREAD

**Issue by tkbsephn** [deadhead420/arch-linux-anywhere#351] opened 2017-05-24 12:27 UTC
Arch Anywhere does not allow me to create a new user with the username "user". When attempting to do so, it gives me an error message ("username already in use").

I had not created a user with such a username.

Is there some way of circumventing this that does not involve changing the username post-installation?

If this is some sort of precautionary measure, would you consider removing the limitation in future releases?

**Comment by pnedkov** [comment] 2017-05-24 18:33
Fixed in #352 
Good catch! Thanks for the report and please test the fix.

**Comment by tkbsephn** [comment] 2017-05-25 09:43
Can now create a user with the username "user".

My screen did go blank after giving the user sudo privileges; however, I am unsure if this is in any way related.

Thank you,  pnedkov.

**Comment by pnedkov** [comment] 2017-05-25 19:01
This must be a separate issue and I cannot reproduce it. Could you please close this issue?

**Closed** 2017-05-26 03:35 UTC
