### ISSUE TITLE
WiFi on install 

### ISSUE THREAD

**Issue by camsn0w** [deadhead420/arch-linux-anywhere#42] opened 2016-06-25 03:36 UTC
The wireless is non working on install..

**Comment by deadhead420** [comment] 2016-06-25 11:41
Impossible. There aren't any issues with wifi in the installer or post install. If you are having issues connection to wifi the issue is your chipset not the installer. Try a different chipset or a wired connection. I would also suggest searching your chipset on google to check for linux support. Sometimes it is required to use win drivers with ndiswrapper... Anyway going to close this issue becuase it is not an issue with the installer. Hope you get it all worked out.

**Closed by deadhead420** 2016-06-25 11:41 UTC

**Comment by camsn0w** [comment] 2016-06-25 21:27
My wifi works fine with antergos, manjaro, debian, ubuntu, tails, kali, chromium os, fedora, redhat, Rebecca black os, centos and everything else on this laptop.

**Comment by deadhead420** [comment] 2016-06-25 22:20
Wifi in the installer or post install?

**Comment by camsn0w** [comment] 2016-06-25 23:44
In the installer it worked fine post install was were the issues were.

**Comment by deadhead420** [comment] 2016-06-26 15:43
This has been reported and isn't really a bug. The options for Wi-Fi utils
are networkmanager and netctl. Neither one comes with a gui. To connect to
Wi-Fi use wifi-menu if you installed netctl and use nmcli if you installed
network manager. I've added back the applet for the next release but for
now you must manage Wi-Fi from the cli or install a gui interface for your
network utility.

**Comment by camsn0w** [comment] 2016-06-26 16:20
The problem is that it says WiFi unmanaged

**Comment by userx-bw** [comment] 2018-11-19 13:07
WIFi Issue, I discovered the "fix" to get it to look for wifi. remove the grep in the line 47 I think it was in the conf file, the strange this is, this is in the preinstall Live boot OS, I can get my public wifi to work on the desktop without issue, I can get the search for repos to work without issue, but when it comes to the installer, forget about it. it fails. to say it is not the script and it is the users issue is a cop out on the developers end. Obviously my drivers in the ios are working for 2 out of 3, so logic says it is the script that is being used to connect to the wifi that is faulty. How? I do not know, I have not even looked at it, let alone know what script(s) to look at. nor should I have to. 

A properly working install script(s) should search, find the wifi then hook up to it, as this is becoming the norm, i fit is not already the norm, in how people hook up to the computers now day, this is not the 90's where no wifi was to be had, and everyone had to use cat5. Cat5 should be the fall back not the go to how Linux Distro wants to look for how to get onto the network and gain an internet connection. 

quote: Try a different chipset or a wired connection. is a lame excuse to not fulfill ones respectability  as a maintainer of a distro. Like I am going to pull my chipset out of my laptop then slap a different one in, fat chance. I am personally dismayed by deadhead420 response to an issue that he can take care of, instead passes off as it is not his problem, I suppose 'deadhead420' does say a lot behind the person behind that name. I'd like to see this resoled by the person that decided to take on developing this distro. 

"We're planning to do the first official release of Anarchy Linux sometime in the next 2-3 days which will include the same arch anywhere installer everyone knows and loves, and also some other big and exciting changes which have been in the works to make Anarchy Linux a distro in its own right."

that is an gross understatement. I do not love your installer, because it does not even work properly.
