### ISSUE TITLE
Is it possible to run this script inside a vanilla Arch Linux ISO?

### ISSUE THREAD

**Issue by julianxhokaxhiu** [deadhead420/arch-linux-anywhere#70] opened 2016-09-25 11:07 UTC
I admit I didn't tested it, but just a feedback is welcome.

Nothing wrong with downloading Arch Linux Anywhere ISO, although would be interesting to know if it works.

Thanks in advance.

**Comment by deadhead420** [comment] 2016-09-25 11:11
It is very well possible! However the script has gotten more complex over time it would require more than simply copy it over and run it. For example it also requires a configuration and language file be copied over. I could create an AUR package which could be used to install arch anywhere on the official archiso (or any arch system for that matter).

**Comment by julianxhokaxhiu** [comment] 2016-09-25 11:43
That sounds awesome! It will also definitely leaverage you from providing always an updated ISO :)

**Comment by TheInitializer** [comment] 2016-10-11 22:28
Sounds great! Notify me when it's done :D

**Comment by 0devnull0** [comment] 2017-01-17 00:00
@deadhead420 That would be indeed a great idea!

**Comment by pnedkov** [comment] 2017-02-05 05:43
I think this will be a great value and I am willing to implement it. Actually I started implementing it by replacing all "/usr/share/arch-anywhere" in arch-installer.sh with a variable that points to either "/usr/share/arch-anywhere" or the absolute path to "arch-installer.sh" based on $0. With a few tweaks I managed to install Arch Linux from the Arch Linux iso using the Arch Anywhere installer.

The problem is the directory structure under arch-linux-anywhere git project is not the same as the directory structure under /usr/share/arch-anywhere/ in the Arch Anywhere iso. Which means the path cannot be easily replaced by a variable.

For example: In the arch-linux-anywhere/ git project ".bashrc" is under extra/ and in the Arch Anywhere iso the same file is directly under /usr/share/arch-anywhere/. The same applies for almost all files.

In order to make the installer portable I will need to make a few simple changes in arch-anywhere-creator.sh as well. Mainly in the "sudo cp..." section.

@deadhead420, please let me know how do you feel about all this. Are you OK with this solution? Thanks!

**Comment by pnedkov** [comment] 2017-02-06 05:26
I implemented this feature and created the pull request: #143

**Comment by pnedkov** [comment] 2017-02-16 00:26
@deadhead420 @condor2 I believe you can close this issue. It works pretty well as described in #143.

**Comment by deadhead420** [comment] 2017-02-16 05:09
Awesome!! Thanks again @pnedkov for your work on the script!!

**Closed by deadhead420** 2017-02-16 05:09 UTC
