### ISSUE TITLE
Installation of xorg-server-utils breaks desktop environment setup completely

### ISSUE THREAD

**Issue by icedream** [deadhead420/arch-linux-anywhere#319] opened 2017-05-08 08:32 UTC
It seems that the [`xorg-server-utils`](https://www.archlinux.org/packages/extra/any/xorg-server-utils/) package that is installed according to `lib/configure_desktop.sh` has been removed and now makes every desktop environment installation in arch-anywhere fail.

**Comment by FredBezies** [comment] 2017-05-08 08:43
Indeed. Xorg-server-utils is now removed. And xorg-utils was removed too :(

**Comment by icedream** [comment] 2017-05-08 09:23
[Further looked into the Arch Linux Wiki](https://wiki.archlinux.org/index.php?title=Xorg&diff=476158&oldid=474175) and it seems that packages that used to be installed with `xorg-server-utils` can now be installed through `xorg-apps`.

**Comment by FredBezies** [comment] 2017-05-08 09:41
Did not noticed that. Thanks for the info.

**Comment by FredBezies** [comment] 2017-05-08 17:12
Can you try to install again after updating arch-anywhere installer? My patch was added. Thanks.

**Comment by sdeleuze** [comment] 2017-05-08 17:42
I confirm the issue is now fixed (failed 2 hours ago, now works flawlessly after an update).

**Comment by FredBezies** [comment] 2017-05-08 17:59
@sdeleuze thanks :)

**Closed** 2017-05-08 18:11 UTC

**Comment by Nabstar** [comment] 2017-05-13 12:28
replacing xorg-server-utils with xorg-apps works like a charm all dependencies present

**Comment by icedream** [comment] 2017-05-14 10:33
So far I can confirm it works like a charm here as well. 👍 Thanks for the fix!
